### ISSUE TITLE
docker run issue

### ISSUE THREAD

**Issue by bulice** [KYVENetwork/evm-snapshots#1]
when start from docker, it show ERROR:
ERROR ❌ Running an invalid version for the specified pool. Version requirements are >=0.1.1.

**Comment by GodOnlyKnowsXZY** [comment]
the same question 
2021-12-15 09:12:14.627  DEBUG [PoolState] Attempting to fetch pool state. 
2021-12-15 09:12:16.237  DEBUG [PoolState] Successfully fetched pool state. 
2021-12-15 09:12:16.247  ERROR ❌ Running an invalid version for the specified pool. Version requirements are >=0.1.1. 
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by fabianriewe** [comment]
To resolve this, please pull the latest version of the Docker image: `docker pull kyve/evm-snapshots:latest`

**Comment by bulice** [comment]
using docker pull kyve/evm-snapshots:latest still meet the same error

**Comment by johnletey** [comment]
@bulice @GodOnlyKnowsXZY What pool are you trying to run on?

**Comment by bulice** [comment]
0x610D55fA573Bce4D2d36e8ADAAee517B785a69dF
https://app.kyve.network/pool/0x610D55fA573Bce4D2d36e8ADAAee517B785a69dF/nodes
this one

**Comment by johnletey** [comment]
@bulice You need to use the [`@kyve/evm`](https://github.com/KYVENetwork/evm) integration. This is the `@kyve/evm-snapshots` integration 😅

**Comment by bulice** [comment]
ok, the evm-snapshots's version is not the same as evm version.

**Comment by fabianriewe** [comment]
We will implement a fix that checks the runtime first and the version second to prevent this error from happening again.

**Comment by bulice** [comment]
That would be better. Thanks.

**Comment by garbirel** [comment]
@kyve/core          = v0.1.3
        @kyve/evm-snapshots = v0.0.2 
2021-12-17 09:43:31.119  DEBUG [PoolState] Attempting to fetch pool state. 
2021-12-17 09:43:36.164  DEBUG [PoolState] Successfully fetched pool state. 
2021-12-17 09:43:36.169  ERROR ❌ Running an invalid version for the specified pool. Version requirements are >=0.1.1. 
error Command failed with exit code 1.

**Comment by garbirel** [comment]
How can I solve this problem？
